name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: santhiya777
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%2300A67E
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2361DAFB

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
